= self-healing-host-based-ssh - High performance computing - self healing host-based SSH login for compute nodes
:source-highlighter: rouge
:rouge-style: gruvbox
:stylesheet: asciidoc.css
:toc: left

== Repositories

* Primary development repository: https://git.ypbind.de/cgit/self-healing-hostbased-ssh
* Backup repository: https://github.com/Bobobo-bo-Bo-bobo/self-healing-hostbased-ssh

== Preface
Distributed computing in a HPC cluster usually requires password-less SSH between the allocated servers of a solver job.

For small environments user are responsible to handle password-less login using their own SSH keys and their own `~/.ssh/authorized_keys` file.

This is not feasible for larger setups. In these environments host-based authentication for password-less connections are in use.
To allow smooth operation the administrators of the clusters are responsible to maintain SSH keys of *all* servers and make sure *all* local `/etc/ssh/ssh_known_hosts` files
are up to date.

Usually this will be archived by:

  * storing and distributing public/private key files for *each* server
  * using the same public/private key for *all* servers

Both solutions are either work intensive and error prone (the former) or plain insecure (the latter, a compromise of a single server will compromise *all* servers).

This proof of concept provides an automated way using MQTT as message broker (in theory any reliable messaging system with a persistent data storage can be used) to
automate updates of `/etc/ssh/ssh_known_hosts` if a new node has been added or any node changes one of it's SSH keys.

== Operational concept
A running and configured MQTT broker with persistent storage is required. Depending on the environment this could even be a https://ypbind.de/maus/notes/mqtt_ha_setup/index.html[high-available MQTT broker^].

Every server runs `ssh-known_hosts-updater` as a service. `ssh-known_hosts-updater` connects to a MQTT broker fetch SSH key information from the MQTT broker on startup and updates the `ssh_known_hosts` if
changes of SSH key of any other server was sent to the MQTT broker.

Also on every server runs `ssh-key-collector` either at startup or at regular intervals, e.g. as systemd timer unit or classic cron job. It's job is to read public SSH keys and send them to the MQTT broker.

If key data should be remove from the MQTT broker `ssh-delete-key_data` can be used to do the job.

== Tools for managing SSH public keys and ssh_known_hosts
This proof of concept comes with three tools to automate SSH key management and MQTT broker interaction.

=== ssh-delete-key_data
`ssh-delete-key_data` removes SSH key data for a list of servers from the persistent storage on the MQTT broker.

Command line options for `ssh-delete-key_data`:

[width="100%",cols="<34%,<41%,<25%",options="header",]
|===
|_Option_ |_Parameter_ |_Note_
|`-C` / `--check` |- | Check syntax of configuration file and exit
|`-D` / `--debug` |- |Show debug messages
|`-V` / `--version` |- |Show version information
|`-c <cfg>` / `--config=<cfg>` |Read configuration from `<cfg>` |Default: `/etc/ssh-delete-key_data.yaml`
|`-h` / `--help` |- |Show help text
|`-q` / `--quiet` |- |Quiet operation. Only warnings and errors are shown
|===

It requires a list of hostnames to be removed from the persistent MQTT storage. The SSH key data is expected to be directly below the topic in the configuration file.
Obviously the MQTT user requires write access to the topic.

The configuration file - default `/etc/ssh-delete-key_data.yaml` - contains the information for the MQTT connection:

[source,yaml]
----
---
mqtt:
  # Mandatory: URL of the MQTT broker, can be tcp:// for MQTT or ssl:// for MQTTS
  broker: 'tcp://localhost:1883'

  # Mandatory: User on MQTT broker for authentication.
  # The user requires write access to the MQTT topic and
  # it's subtopics (at least one level)
  user: 'ssh-pubkey-publisher'

  # Mandatory: Password for MQTT broker for authentication
  password: 'S3cr3t'

  # QoS for MQTT messages
  # Default: 0
  qos: 0

  # Mandatory: MQTT topic containing the SSH key data (<topic>/<servername>)
  topic: 'ssh/pub/keys'

  # Optional: For SSL encrypted connection, the path to the
  # CA file for validation of the server certificate
  ca_cert: '/path/to/ca-cert.crt'

  # Optional: Clean session information on connect or reconnect.
  # Very seldom useful. Default: false
  clean_session: false

  # Optional: Set MQTT client id. MQTT standard limits the client ID to 23 bytes of ASCII data
  # !!! ATTENTION !!! The client id *MUST* *BE* *UNIQUE*!
  # If not set, a random 23 byte alphanumeric client ID will be generated
  # client_id: 'unique_client_id'

  # Optional: Disable SSL verification of the MQTT broker SSL certificate.
  # Should not be used in a productive environment
  # Default: false
  insecure_ssl: false

  # Optional: Timeout in seconds for MQTT connect and reconnects
  # A value of 0 will cause connect/reconnect to try indefinitely (should be used with care)
  reconnect_timeout: 60
----

=== ssh-key-collector
`ssh-key-collector` reads SSH public keys - by default matching `/etc/ssh/ssh_host_.*_key.pub` - and send the content to the MQTT broker.
By default the hostname field for `ssh_known_host` will be set to the output of the `hostname` command but can be overridden.

This command should be at least run at startup and can optionally be run at regular intervals, e.g. as cron job or systemd timer unit.

Command line options for `ssh-key-collector` are:

[width="100%",cols="<34%,<41%,<25%",options="header",]
|===
|_Option_ |_Parameter_ |_Note_
|`-C` / `--check` |- | Check syntax of configuration file and exit
|`-D` / `--debug` |- |Show debug messages
|`-V` / `--version` |- |Show version information
|`-c <cfg>` / `--config=<cfg>` |Read configuration from `<cfg>` |Default: `/etc/ssh-key-collector.yaml`
|`-h` / `--help` |- |Show help text
|`-q` / `--quiet` |- |Quiet operation. Only warnings and errors are shown
|===

The configuration file - default is `/etc/ssh-key-collector.yaml` - contains the MQTT connection options and optional overrides
for SSH file or data for the `ssh_known_hosts` file:

[source,yaml]
----
---
mqtt:
  # Mandatory: URL of the MQTT broker, can be tcp:// for MQTT or ssl:// for MQTTS
  broker: 'tcp://localhost:1883'

  # Mandatory: User on MQTT broker for authentication.
  # The user requires write access to the MQTT topic and
  # it's subtopics (at least one level)
  user: 'ssh-pubkey-publisher'

  # Mandatory: Password for MQTT broker for authentication
  password: 'S3cr3t'

  # QoS for MQTT messages
  # Default: 0
  qos: 0

  # Mandatory: MQTT topic containing the SSH key data (<topic>/<servername>)
  topic: 'ssh/pub/keys'

  # Optional: For SSL encrypted connection, the path to the
  # CA file for validation of the server certificate
  ca_cert: '/path/to/ca-cert.crt'

  # Optional: Clean session information on connect or reconnect.
  # Very seldom useful. Default: false
  clean_session: false

  # Optional: Set MQTT client id. MQTT standard limits the client ID to 23 bytes of ASCII data
  # !!! ATTENTION !!! The client id *MUST* *BE* *UNIQUE*!
  # If not set, a random 23 byte alphanumeric client ID will be generated
  # client_id: 'unique_client_id'

  # Optional: Disable SSL verification of the MQTT broker SSL certificate.
  # Should not be used in a productive environment
  # Default: false
  insecure_ssl: false

  # Optional: Timeout in seconds for MQTT connect and reconnects
  # A value of 0 will cause connect/reconnect to try indefinitely (should be used with care)
  reconnect_timeout: 60

# Optional: Overrides and/or additional information for SSH keys
ssh-keys:
  # Optional: List of SSH public keys to be published.
  # Default: Every file matching /etc/ssh/ssh_host_.*_key.pub
  files:
    - '/etc/ssh/ssh_host_ecdsa_key.pub'
    - '/etc/ssh/ssh_host_ed25519_key.pub'
    - '/etc/ssh/ssh_host_rsa_key.pub'

  # Optional: Override hostname field to be used in ssh_known_hosts
  # Default: hostname
  hostname:
    - 'server'
    - '10.1.2.3'
    - 'server.fqdn'

  # Optional: Override the comment field in ssh_known_hosts.
  # Default: comment from public key file
  comment: 'this is a comment'
----

=== ssh-known_hosts-updater
`ssh-known_hosts-updater` is a service maintaining a persistent MQTT connection to the broker. Upon start of the MQTT connection, it receives all persistent MQTT data from the broker and updates the `ssh_known_hosts` file.
If any SSH key changes - by `ssh-key-collector` - or removals - by `ssh-delete-key_data` - are received, the `ssh_known_hosts` will be rewritten accordingly.

By default the `ssh_known_hosts` file is `/etc/ssh/ssh_known_hosts` but this can be overridden in the configuration file.

`ssh-known_hosts-updater` accepts the following command line parameters:

[width="100%",cols="<34%,<41%,<25%",options="header",]
|===
|_Option_ |_Parameter_ |_Note_
|`-C` / `--check` |- | Check syntax of configuration file and exit
|`-D` / `--debug` |- |Show debug messages
|`-V` / `--version` |- |Show version information
|`-c <cfg>` / `--config=<cfg>` |Read configuration from `<cfg>` |Default: `/etc/ssh-known_hosts-updater.yaml`
|`-h` / `--help` |- |Show help text
|`-q` / `--quiet` |- |Quiet operation. Only warnings and errors are shown
|===

The configuration file - default `/etc/ssh-known_hosts-updater.yaml` - contains at least the MQTT connection parameters and optionally the location of the `ssh_known_hosts` file (default is `/etc/ssh/ssh_known_hosts`):

[source,yaml]
----
---
mqtt:
  # Mandatory: URL of the MQTT broker, can be tcp:// for MQTT or ssl:// for MQTTS
  broker: 'tcp://localhost:1883'

  # Mandatory: User on MQTT broker for authentication.
  # The user requires read access to the MQTT topic
  # and subtopics
  user: 'ssh-known_hosts_updater'

  # Mandatory: Password for MQTT broker for authentication
  password: 'S3cr3t'

  # QoS for MQTT messages
  # Default: 0
  qos: 0

  # Mandatory: MQTT topic containing the SSH key data (<topic>/<servername>)
  # This topic *must* contain wildcards
  topic: 'ssh/pub/keys/+'

  # Optional: For SSL encrypted connection, the path to the
  # CA file for validation of the server certificate
  ca_cert: '/path/to/ca-cert.crt'

  # Optional: Clean session information on connect or reconnect.
  # Very seldom useful. Default: false
  clean_session: false

  # Optional: Set MQTT client id. MQTT standard limits the client ID to 23 bytes of ASCII data
  # !!! ATTENTION !!! The client id *MUST* *BE* *UNIQUE*!
  # If not set, a random 23 byte alphanumeric client ID will be generated
  # client_id: 'unique_client_id'

  # Optional: Disable SSL verification of the MQTT broker SSL certificate.
  # Should not be used in a productive environment
  # Default: false
  insecure_ssl: false

  # Optional: Timeout in seconds for MQTT connect and reconnects
  # A value of 0 will cause connect/reconnect to try indefinitely (should be used with care)
  reconnect_timeout: 60

# Optional: Override default settings for SSH
ssh:
  # Optional: SSH known hosts file.
  # Default: /etc/ssh/ssh_known_hosts
  known_hosts_file: '/etc/ssh/ssh_known_hosts'
----

== Lifecycle of servers (in terms of SSH keys)
In terms of SSH keys, the lifecycle of a server can be broken down into three parts:

* adding a new server - new SSH keys must be added to `/etc/ssh/ssh_known_hosts` on all servers
* reinstalling a server - keys will be regenerated and must be updated in `/etc/ssh/ssh_known_hosts` on all servers
* decommissioning a server - keys must be removed from the brokers persistent storage and from `/etc/ssh/ssh_known_hosts` of all servers

=== Adding a new server
After the installation and configuration of a new server, `ssh-key-collector` will send the new public SSH host keys to the MQTT broker.
The `ssh-known_hosts-updater` service on the new server will publish the `ssh_known_hosts` file with key data from the MQTT broker and
the `ssh-known_hosts-updater` on all other servers will receive the new SSH public keys via MQTT and update their `ssh_known_hosts` file accordingly.

Servers currently offline will receive the new data upon start of `ssh-known_hosts-updater` which will update the `ssh_known_hosts` file.

=== Reinstalling a server
If a server was reinstalled, the SSH service usually generate new SSH key pairs. The next run of `ssh-key-collector` will send the new SSH public keys to the MQTT broker.
All servers running `ssh-known_hosts-updater` will receive the changed public keys and update their `ssh_known_hosts` file accordingly.

Servers currently offline will receive the new data upon start of `ssh-known_hosts-updater` which will update the `ssh_known_hosts` file.

=== Decommissioning a server
Although public SSH keys are not sensitive information, old SSH key data should be removed to reduce disk consumption of the persistent storage on the MQTT broker.
Either the client tool, e.g. `mosquitto_pub` can be used to remove persistent data or `ssh-delete-key_data` can be used for this specific task.

Upon removal, all servers running `ssh-known_hosts-updater` will receive a notification of the removal (an empty, persistent MQTT message) and update their `ssh_known_host` file.

Servers currently offline will receive the new data upon start of `ssh-known_hosts-updater` which will update the `ssh_known_hosts` file.

== FAQ
=== Which QoS to use
MQTT has three values for QoS:

* 0 - no confirmation
* 1 - broker confirms message received
* 2 - broker confirms message received and client confirms confirmation receival

In an HPC environment, (ethernet) network can be considered as reliable. To reduce overhead, a QoS of 0 is sufficient.

=== Removal/reinitialisation of persistent storage on MQTT broker
Because the MQTT broker stores the persistent messages on disk - including public SSH key data - the content and consistency of the on-disk storage
is critical.

If - for any reason - the persistent storage of the MQTT broker must be removed or reinitialised, special care must be taken to ensure integrity of `ssh_known_hosts` files on the servers.
It must be made sure, know server reboots or `ssh-known_hosts-updater` are restarted on any server before *all* public SSH keys are recollected, e.g. by running `ssh-key-collector` on
all affected servers.

For smooth operation, it's important to fetch all public SSH keys from all cluster servers by running `ssh-key-collector` on all servers.

=== Structuring grouping instead of a flat hierarchy
Instead of a flat hierarchy public key data can be grouped by using MQTT topics. Additionaly, different MQTT user with separate ACL rules can be configured, e.g.:

* Cluster CLU-001: Topic: `corp/cluster/ssh_keys/clu-001`, Users: `ssh-key-collector-clu-001` for `ssh-key-collector` / `ssh-known_hosts-updater-clu-001` for `ssh-known_hosts-updater` and `ssh-delete-key_data-clu-001` for `ssh-delete-key_data`
* Cluster CLU-002: Topic: `corp/cluster/ssh_keys/clu-002`, Users: `ssh-key-collector-clu-002` for `ssh-key-collector` / `ssh-known_hosts-updater-clu-002` for `ssh-known_hosts-updater` and `ssh-delete-key_data-clu-002` for `ssh-delete-key_data`
* Cluster CLU-003: Topic: `corp/cluster/ssh_keys/clu-003`, Users: `ssh-key-collector-clu-003` for `ssh-key-collector` / `ssh-known_hosts-updater-clu-003` for `ssh-known_hosts-updater` and `ssh-delete-key_data-clu-003` for `ssh-delete-key_data`
* Cluster CLU-004: Topic: `corp/cluster/ssh_keys/clu-004`, Users: `ssh-key-collector-clu-004` for `ssh-key-collector` / `ssh-known_hosts-updater-clu-004` for `ssh-known_hosts-updater` and `ssh-delete-key_data-clu-004` for `ssh-delete-key_data`
